### ISSUE TITLE
Add Wave to installer procedure

### ISSUE THREAD

**Issue by pditommaso** [seqeralabs/seqera-installer#4]
The installer procedure should include an optional step to enable the configuration of Wave in the Seqera Platform deployment 
```[tasklist]
### Tasks
- [ ] Add scripts and config files for local deployment
- [ ] Add scripts and config files for aws eks deployment
- [ ] Add scripts and config files for aws ec2 deployment
```
